-- Generated by api-data-gen
-- Generation tag: RUN20260302
SET NAMES utf8mb4;

-- Validation checks
-- [PASS] cross_table:alert_date alert_date expected 2020-12-20; actual aml_f_wst_alert_cust_drft_record=['2020-12-20']; aml_f_wst_alert_cust_trans_info=['2020-12-20']
-- [PASS] cross_table:cust_id cust_id expected 962020122711000002; actual aml_f_tidb_model_result=['962020122711000002']; aml_f_wst_alert_cust_drft_record=['962020122711000002']; aml_f_wst_alert_cust_trans_info=['962020122711000002']
-- [PASS] cross_table:model_key model_key expected WSTY001; actual aml_f_tidb_model_result=['WSTY001']; aml_f_wst_alert_cust_drft_record=['WSTY001']; aml_f_wst_alert_cust_trans_info=['WSTY001']
-- [PASS] shared_column:drft_no drft_no shared intersection ['510355201611120250722102158993_000009189488_0000093478']; actual aml_f_wst_alert_cust_drft_record=['510355201611120250722102158993_000009189488_0000093478']; aml_f_wst_alert_cust_trans_info=['510355201611120250722102158993_000009189488_0000093478']
-- [PASS] shared_column:ds ds shared intersection ['2020-12-20']; actual aml_f_tidb_model_result=['2020-12-20']; aml_f_wst_alert_cust_drft_record=['2020-12-20']; aml_f_wst_alert_cust_trans_info=['2020-12-20']

START TRANSACTION;

USE `aml_new3`;
INSERT INTO `aml_f_tidb_model_result` (`uuid`, `result_key`, `model_key`, `model_type`, `cust_id`, `result_date`, `cust_model_result`, `model_seq`, `model_version`, `ds`) VALUES
  ('AMLFTIDB_D136AE_001', 'WSTY0012020-12-20962020122711000002', 'WSTY001', 'BS', '962020122711000002', '2020-12-27', '1', '20201220001', '1.0', '2020-12-20'),
  ('AMLFTIDB_D136AE_002', 'WSTY0012020-11-259620220922110010', 'WSTY001', 'BS', '962020122711000002', '2020-12-27', '1', '20201125001', '1.0', '2020-12-20');

INSERT INTO `aml_f_wst_alert_cust_trans_info` (`uuid`, `cust_id`, `model_key`, `alert_date`, `transactionkey`, `trans_time`, `cust_name`, `receive_pay_cd`, `trans_amount`, `drft_no`, `last_req_nm`, `drwr_nm`, `ds`) VALUES
  ('AMLFWSTA_D136AE_001', '962020122711000002', 'WSTY001', '2020-12-20', '2012100170247697657UC0FIQKKIU6TD-1', '2020-11-26 09:48:54', '辽宁麒麟湾体育公司', '01', 129876.4000, '510355201611120250722102158993_000009189488_0000093478', '深圳纸杯伈制造技忄有彡公司', '深圳纸杯誋制造技忄有彡公司', '2020-12-20'),
  ('AMLFWSTA_D136AE_002', '962020122711000002', 'WSTY001', '2020-12-20', '2012100170247697657UC0FIQKKIU6TD-2', '2020-11-26 09:47:54', '辽宁麒麟湾体育公司', '02', 98765.4300, '510355201611120250722102158993_000009189488_0000093478', '北京天安科技公司', '上海浦东发展公司', '2020-12-20'),
  ('AMLFWSTA_D136AE_003', '962020122711000002', 'WSTY001', '2020-12-20', '2012100170247697657UC0FIQKKIU6TD-13', '2020-11-26 10:45:54', '辽宁麒麟湾体育公司', '01', 129876.4000, '510355201611120250722102158993_000009189488_0000093478', '深圳纸杯伈制造技忄有彡公司', '深圳纸杯誋制造技忄有彡公司', '2020-12-20');

INSERT INTO `aml_f_wst_alert_cust_drft_record` (`uuid`, `cust_id`, `model_key`, `alert_date`, `drft_no`, `seq_no`, `msg_typ`, `req_nm`, `rcv_nm`, `sgn_up_dt`, `ds`) VALUES
  ('AMLFWSTA_D136AE_001', '962020122711000002', 'WSTY001', '2020-12-20', '510355201611120250722102158993_000009189488_0000093478', '8', '背书', '辽宁屿东城体育公司', '辽宁麒麟湾体育公司', '20200724', '2020-12-20'),
  ('AMLFWSTA_D136AE_002', '962020122711000002', 'WSTY001', '2020-12-20', '510355201611120250722102158993_000009189488_0000093478', '7', '背书', '大连上自称有限公司', '辽宁屿东城体育公司', '20200721', '2020-12-20'),
  ('AMLFWSTA_D136AE_003', '962020122711000002', 'WSTY001', '2020-12-20', '510355201611120250722102158993_000009189488_0000093478', '10', '背书', '北京天安科技公司', '上海浦东发展公司', '20200725', '2020-12-20');

COMMIT;
