-- Generated by api-data-gen
SET NAMES utf8mb4;

-- Validation checks
-- [PASS] custTransInfo:baseline:cross_table:cust_id cust_id expected 962020122711000002; actual aml_f_tidb_model_result=['962020122711000002']; aml_f_wst_alert_cust_trans_info=['962020122711000002']
-- [PASS] custTransInfo:baseline:cross_table:model_key model_key expected WSTY001; actual aml_f_tidb_model_result=['WSTY001']; aml_f_wst_alert_cust_trans_info=['WSTY001']
-- [PASS] custTransInfo:baseline:shared_column:ds ds shared intersection ['2020-12-20']; actual aml_f_tidb_model_result=['2020-12-20']; aml_f_wst_alert_cust_trans_info=['2020-12-20']
-- [PASS] custTransInfo:pagination:cross_table:cust_id cust_id expected 962020122711000002; actual aml_f_tidb_model_result=['962020122711000002']; aml_f_wst_alert_cust_trans_info=['962020122711000002']
-- [PASS] custTransInfo:pagination:cross_table:model_key model_key expected WSTY001; actual aml_f_tidb_model_result=['WSTY001']; aml_f_wst_alert_cust_trans_info=['WSTY001']
-- [PASS] custTransInfo:pagination:shared_column:ds ds shared intersection ['2020-12-20']; actual aml_f_tidb_model_result=['2020-12-20']; aml_f_wst_alert_cust_trans_info=['2020-12-20']
-- [PASS] custTransInfo:dictionary:cross_table:cust_id cust_id expected 962020122711000002; actual aml_f_tidb_model_result=['962020122711000002']; aml_f_wst_alert_cust_trans_info=['962020122711000002']
-- [PASS] custTransInfo:dictionary:cross_table:model_key model_key expected WSTY001; actual aml_f_tidb_model_result=['WSTY001']; aml_f_wst_alert_cust_trans_info=['WSTY001']
-- [PASS] custTransInfo:dictionary:shared_column:ds ds shared intersection ['2020-12-20']; actual aml_f_tidb_model_result=['2020-12-20']; aml_f_wst_alert_cust_trans_info=['2020-12-20']

START TRANSACTION;

-- Scenario: custTransInfo:baseline custTransInfo baseline replay
USE `aml_new3`;
INSERT INTO `aml_f_tidb_model_result` (`uuid`, `result_key`, `model_key`, `model_type`, `cust_id`, `result_date`, `cust_model_result`, `model_seq`, `model_version`, `ds`) VALUES
  ('AMLFTIDB_2FA35C_001', 'WSTY0012020-12-20962020122711000002', 'WSTY001', 'BS', '962020122711000002', '2020-12-27', '1', '', '1.0', '2020-12-20'),
  ('AMLFTIDB_2FA35C_002', 'WSTY0012020-11-259620220922110010', 'WSTY001', 'BS', '962020122711000002', '2020-12-27', '1', '', '1.0', '2020-12-20'),
  ('AMLFTIDB_2FA35C_003', 'WSTY0012020-12-20962020122711000002', 'WSTY001', 'BS', '962020122711000002', '2020-12-27', '1', '', '1.0', '2020-12-20');

INSERT INTO `aml_f_wst_alert_cust_trans_info` (`uuid`, `cust_id`, `model_key`, `alert_date`, `transactionkey`, `trans_time`, `cust_name`, `receive_pay_cd`, `trans_amount`, `drft_no`, `last_req_nm`, `drwr_nm`, `ds`) VALUES
  ('AMLFWSTA_2FA35C_001', '962020122711000002', 'WSTY001', '2020-12-20', '6008C20260303000006003532899996', '2020-11-26 09:48:54', '辽宁麒麟湾体育公司', '01', 129876.4000, '510355201611120250722102158993_000009189488_0000093478', '深圳纸杯伈制造技忄有彡公司', '深圳纸杯誋制造技忄有彡公司', '2020-12-20'),
  ('AMLFWSTA_2FA35C_002', '962020122711000002', 'WSTY001', '2020-12-20', '6008C20260303000006006507299996', '2020-11-26 09:47:54', '辽宁麒麟湾体育公司', '02', 98765.4300, '510355201611120250722102158993_000009189488_0000093479', '北京天安科技公司', '上海浦东发展公司', '2020-12-20'),
  ('AMLFWSTA_2FA35C_003', '962020122711000002', 'WSTY001', '2020-12-20', '6008C20260303000006007674699996', '2020-11-26 10:45:54', '辽宁麒麟湾体育公司', '01', 129876.4000, '510355201611120250722102158993_000009189488_0000093478', '深圳纸杯伈制造技忄有彡公司', '深圳纸杯誋制造技忄有彡公司', '2020-12-20');


-- Scenario: custTransInfo:pagination custTransInfo pagination stability
INSERT INTO `aml_f_tidb_model_result` (`uuid`, `result_key`, `model_key`, `model_type`, `cust_id`, `result_date`, `cust_model_result`, `model_seq`, `model_version`, `ds`) VALUES
  ('AMLFTIDB_4091D4_001', 'WSTY0012020-12-20962020122711000002', 'WSTY001', 'BS', '962020122711000002', '2020-12-27', '1', '', '1.0', '2020-12-20'),
  ('AMLFTIDB_4091D4_002', 'WSTY0012020-11-259620220922110010', 'WSTY001', 'BS', '962020122711000002', '2020-12-27', '1', '', '1.0', '2020-12-20'),
  ('AMLFTIDB_4091D4_003', 'WSTY0012020-12-20962020122711000002', 'WSTY001', 'BS', '962020122711000002', '2020-12-27', '1', '', '1.0', '2020-12-20');

INSERT INTO `aml_f_wst_alert_cust_trans_info` (`uuid`, `cust_id`, `model_key`, `alert_date`, `transactionkey`, `trans_time`, `cust_name`, `receive_pay_cd`, `trans_amount`, `drft_no`, `last_req_nm`, `drwr_nm`, `ds`) VALUES
  ('AMLFWSTA_4091D4_001', '962020122711000002', 'WSTY001', '2020-12-20', '6008C20260303000006009976299996', '2020-11-26 09:48:54', '辽宁麒麟湾体育公司', '01', 129876.4000, '510355201611120250722102158993_000009189488_0000093478', '深圳纸杯伈制造技忄有彡公司', '深圳纸杯誋制造技忄有彡公司', '2020-12-20'),
  ('AMLFWSTA_4091D4_002', '962020122711000002', 'WSTY001', '2020-12-20', '6008C20260303000006004644599996', '2020-11-26 09:47:54', '辽宁麒麟湾体育公司', '02', 98765.4300, '510355201611120250722102158993_000009189488_0000093479', '北京天安科技公司', '上海浦东发展公司', '2020-12-20'),
  ('AMLFWSTA_4091D4_003', '962020122711000002', 'WSTY001', '2020-12-20', '6008C20260303000006002334999996', '2020-11-26 10:45:54', '辽宁麒麟湾体育公司', '01', 129876.4000, '510355201611120250722102158993_000009189488_0000093478', '深圳纸杯伈制造技忄有彡公司', '深圳纸杯誋制造技忄有彡公司', '2020-12-20');


-- Scenario: custTransInfo:dictionary custTransInfo dictionary consistency
INSERT INTO `aml_f_tidb_model_result` (`uuid`, `result_key`, `model_key`, `model_type`, `cust_id`, `result_date`, `cust_model_result`, `model_seq`, `model_version`, `ds`) VALUES
  ('AMLFTIDB_0BDF11_001', 'WSTY0012020-12-20962020122711000002', 'WSTY001', 'BS', '962020122711000002', '2020-12-27', '1', '', '1.0', '2020-12-20'),
  ('AMLFTIDB_0BDF11_002', 'WSTY0012020-11-259620220922110010', 'WSTY001', 'BS', '962020122711000002', '2020-12-27', '1', '', '1.0', '2020-12-20'),
  ('AMLFTIDB_0BDF11_003', 'WSTY0012020-12-20962020122711000002', 'WSTY001', 'BS', '962020122711000002', '2020-12-27', '1', '', '1.0', '2020-12-20');

INSERT INTO `aml_f_wst_alert_cust_trans_info` (`uuid`, `cust_id`, `model_key`, `alert_date`, `transactionkey`, `trans_time`, `cust_name`, `receive_pay_cd`, `trans_amount`, `drft_no`, `last_req_nm`, `drwr_nm`, `ds`) VALUES
  ('AMLFWSTA_0BDF11_001', '962020122711000002', 'WSTY001', '2020-12-20', '6008C20260303000006006233699996', '2020-11-26 09:48:54', '辽宁麒麟湾体育公司', '01', 129876.4000, '510355201611120250722102158993_000009189488_0000093478', '深圳纸杯伈制造技忄有彡公司', '深圳纸杯誋制造技忄有彡公司', '2020-12-20'),
  ('AMLFWSTA_0BDF11_002', '962020122711000002', 'WSTY001', '2020-12-20', '6008C20260303000006003909299996', '2020-11-26 09:47:54', '辽宁麒麟湾体育公司', '02', 98765.4300, '510355201611120250722102158993_000009189488_0000093479', '北京天安科技公司', '上海浦东发展公司', '2020-12-20'),
  ('AMLFWSTA_0BDF11_003', '962020122711000002', 'WSTY001', '2020-12-20', '6008C20260303000006006924899996', '2020-11-26 10:45:54', '辽宁麒麟湾体育公司', '01', 129876.4000, '510355201611120250722102158993_000009189488_0000093478', '深圳纸杯伈制造技忄有彡公司', '深圳纸杯誋制造技忄有彡公司', '2020-12-20');

COMMIT;
