from __future__ import annotations

import re

from api_data_gen.domain.models import GeneratedTable, ValidationCheck


_GENERIC_SCENARIO_TITLE_RE = re.compile(r"^(?:ai\s*)?scenario\s*\d+$", re.IGNORECASE)


class SqlScriptExportService:
    _SCENARIO_HEADER_RE = re.compile(r"^-- Scenario:\s+(\S+)", re.MULTILINE)

    def __init__(self, table_locator):
        self._table_locator = table_locator

    def render(
        self,
        generated_tables: list[GeneratedTable],
        validation_checks: list[ValidationCheck],
        generation_tag: str = "",
    ) -> str:
        return self._render(
            generated_tables=generated_tables,
            validation_checks=validation_checks,
            generation_tag=generation_tag,
            include_file_header=True,
            batch_label="",
        )

    def append_missing_scenarios(
        self,
        existing_script: str,
        generated_tables: list[GeneratedTable],
        validation_checks: list[ValidationCheck],
        generation_tag: str = "",
        batch_label: str = "",
    ) -> str:
        existing_scenarios = self.extract_scenario_ids(existing_script)
        missing_tables = _filter_missing_scenario_tables(generated_tables, existing_scenarios)
        if not existing_script.strip():
            return self.render(
                generated_tables=generated_tables,
                validation_checks=validation_checks,
                generation_tag=generation_tag,
            )
        if not missing_tables:
            return existing_script
        append_block = self._render(
            generated_tables=missing_tables,
            validation_checks=validation_checks,
            generation_tag=generation_tag,
            include_file_header=False,
            batch_label=batch_label,
        )
        return existing_script.rstrip() + "\n\n" + append_block

    @classmethod
    def extract_scenario_ids(cls, script: str) -> set[str]:
        return {match.group(1).strip() for match in cls._SCENARIO_HEADER_RE.finditer(script) if match.group(1).strip()}

    def _render(
        self,
        generated_tables: list[GeneratedTable],
        validation_checks: list[ValidationCheck],
        generation_tag: str,
        include_file_header: bool,
        batch_label: str,
    ) -> str:
        lines = ["-- Generated by api-data-gen"]
        if not include_file_header:
            lines = [f"-- Appended batch: {batch_label or 'append'}"]
        if generation_tag:
            lines.append(f"-- Generation tag: {generation_tag}")
        if include_file_header:
            lines.extend([
                "SET NAMES utf8mb4;",
                "",
            ])
        else:
            lines.append("")
        lines.extend(self._render_validation_checks(validation_checks))
        lines.append("START TRANSACTION;")
        lines.append("")

        current_schema = None
        current_scenario = None
        for generated_table in generated_tables:
            if not generated_table.insert_sql:
                continue
            scenario_key = (
                generated_table.scenario_id,
                _display_scenario_title(generated_table.scenario_title, generated_table.scenario_objective),
                generated_table.scenario_objective,
            )
            if scenario_key != current_scenario and any(scenario_key[:2]):
                if current_scenario is not None:
                    lines.append("")
                lines.extend(_render_scenario_header(generated_table))
                current_scenario = scenario_key
            schema_name, _ = self._table_locator.resolve_table_location(generated_table.table_name)
            if schema_name != current_schema:
                if current_schema is not None:
                    lines.append("")
                lines.append(f"USE `{schema_name}`;")
                current_schema = schema_name
            lines.extend(generated_table.insert_sql)
            lines.append("")

        lines.append("COMMIT;")
        return "\n".join(lines).rstrip() + "\n"

    @staticmethod
    def _render_validation_checks(validation_checks: list[ValidationCheck]) -> list[str]:
        if not validation_checks:
            return []

        lines = ["-- Validation checks"]
        for check in validation_checks:
            status = "PASS" if check.passed else "FAIL"
            detail = f" {check.detail}" if check.detail else ""
            lines.append(f"-- [{status}] {check.name}{detail}")
        lines.append("")
        return lines


def _render_scenario_header(generated_table: GeneratedTable) -> list[str]:
    display_title = _display_scenario_title(generated_table.scenario_title, generated_table.scenario_objective)
    source_label = _source_label(generated_table.generation_source)
    header = f"-- Scenario: {generated_table.scenario_id or '[no-id]'} {display_title}{source_label}".rstrip()
    lines = [header]
    objective = " ".join((generated_table.scenario_objective or "").split())
    if objective and objective != display_title:
        lines.append(f"-- Objective: {objective}")
    return lines


def _display_scenario_title(title: str, objective: str) -> str:
    normalized_title = " ".join((title or "").split())
    normalized_objective = " ".join((objective or "").split())
    if normalized_title and not _GENERIC_SCENARIO_TITLE_RE.fullmatch(normalized_title):
        return normalized_title
    if normalized_objective:
        for separator in (" - ", "; ", ". ", ", "):
            if separator in normalized_objective:
                normalized_objective = normalized_objective.split(separator, 1)[0].strip()
                break
        return normalized_objective[:120].rstrip(" .;,-")
    return normalized_title or "scenario"


def _source_label(generation_source: str) -> str:
    if generation_source == "ai":
        return " [AI generated]"
    if generation_source == "hybrid":
        return " [Hybrid: AI scenario + local data]"
    if generation_source == "local":
        return " [Local generated]"
    return ""


def _filter_missing_scenario_tables(
    generated_tables: list[GeneratedTable],
    existing_scenarios: set[str],
) -> list[GeneratedTable]:
    if not existing_scenarios:
        return list(generated_tables)
    filtered: list[GeneratedTable] = []
    for generated_table in generated_tables:
        scenario_id = (generated_table.scenario_id or "").strip()
        if not scenario_id or scenario_id not in existing_scenarios:
            filtered.append(generated_table)
    return filtered
