from __future__ import annotations

from api_data_gen.domain.models import GeneratedTable, ValidationCheck


class SqlScriptExportService:
    def __init__(self, table_locator):
        self._table_locator = table_locator

    def render(
        self,
        generated_tables: list[GeneratedTable],
        validation_checks: list[ValidationCheck],
        generation_tag: str = "",
    ) -> str:
        lines = [
            "-- Generated by api-data-gen",
        ]
        if generation_tag:
            lines.append(f"-- Generation tag: {generation_tag}")
        lines.extend(
            [
                "SET NAMES utf8mb4;",
                "",
            ]
        )
        lines.extend(self._render_validation_checks(validation_checks))
        lines.append("START TRANSACTION;")
        lines.append("")

        current_schema = None
        current_scenario = None
        for generated_table in generated_tables:
            if not generated_table.insert_sql:
                continue
            scenario_key = (generated_table.scenario_id, generated_table.scenario_title)
            if scenario_key != current_scenario and any(scenario_key):
                if current_scenario is not None:
                    lines.append("")
                lines.append(
                    f"-- Scenario: {generated_table.scenario_id or '[NO_ID]'} "
                    f"{generated_table.scenario_title}".rstrip()
                )
                current_scenario = scenario_key
            schema_name, _ = self._table_locator.resolve_table_location(generated_table.table_name)
            if schema_name != current_schema:
                if current_schema is not None:
                    lines.append("")
                lines.append(f"USE `{schema_name}`;")
                current_schema = schema_name
            lines.extend(generated_table.insert_sql)
            lines.append("")

        lines.append("COMMIT;")
        return "\n".join(lines).rstrip() + "\n"

    @staticmethod
    def _render_validation_checks(validation_checks: list[ValidationCheck]) -> list[str]:
        if not validation_checks:
            return []

        lines = ["-- Validation checks"]
        for check in validation_checks:
            status = "PASS" if check.passed else "FAIL"
            detail = f" {check.detail}" if check.detail else ""
            lines.append(f"-- [{status}] {check.name}{detail}")
        lines.append("")
        return lines
